name: vetkonect
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+7.2

environment:
  sdk: ^3.5.4


dependencies:
  flutter:
    sdk: flutter


  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  get: ^4.6.6
  http: ^1.2.2
  carousel_slider: ^5.0.0
  flutter_rating_bar: ^4.0.0
  google_sign_in: ^6.1.0
  shared_preferences: ^2.0.6
  flutter_svg: ^2.0.7
  animate_do: ^3.1.2
  dio: ^5.0.0
  icons_plus: ^5.0.0
  image_picker: ^1.1.2
  sign_in_with_apple: ^6.1.3
  get_storage: ^2.0.3
  permission_handler: ^11.3.1
  url_launcher: ^6.1.7
  webview_flutter: ^4.0.0
  webview_flutter_android: ^4.1.0
  font_awesome_flutter: ^10.1.0
  flutter_secure_storage: ^9.2.2
  country_state_city_picker: ^1.0.0
  flutter_facebook_auth: ^7.1.1
  connectivity_plus: ^6.1.1
  keep_screen_on: ^3.0.0
  flutter_launcher_icons: ^0.13.1
  package_rename: ^1.8.0
  csc_picker: ^0.2.7

flutter_icons:
  android: true
  ios: true
  image_path: 'assets/images/new_logo.png'

android:
  app_name: vetkonect
  package_name: www.vetkonect.com
  override_old_package: com.vetkonect

dev_dependencies:
  flutter_test:
    sdk: flutter

 
  flutter_lints: ^4.0.0

# The following section is specific to Flutter packages.
flutter:


  uses-material-design: true


  assets:
    - assets/images/pet_care.jpeg
    - assets/images/animal_health.jpeg
    - assets/images/vet_clinic.jpeg
    - assets/images/login_logo.jpeg
    - assets/images/search_icon.jpeg
